### ISSUE TITLE
[As an] Assessor [I want to] be able to specify when I want to add a new address, amend an existing address and get the full details of an existing address [so] that I can lodge the certificate to the correct property

### ISSUE THREAD

**Issue by A-thorpe** [notbinary/mhclg-epc-alpha#136]
Currently the 'Add new address' feature is what assessors use to:
- Add a new address
- Amend a new address

 This should be separated as it can be confusing for new assessors.

**Comment by mcoulthurst** [comment]
The auth user prototype includes a page to **add** a new address for assessors:
https://mhclg-epc-alpha-prototype-02.herokuapp.com/add-address
There is also a path to find an address and **amend** the details:
https://mhclg-epc-alpha-prototype-02.herokuapp.com/find-address (need to step through the flow to see this)
