### ISSUE TITLE
[As an] Assessor [I want to] have the ability to generate an EPC certificate based on figures gathered during the assessment of a property [so that] I can pass the official certificate on the my client 

### ISSUE THREAD

**Issue by A-thorpe** [notbinary/mhclg-epc-alpha#173]
Core functionality needed for the register services to be of use going forward

**Comment by mcoulthurst** [comment]
Mocked up a flow to lodge data directly via the website:
https://mhclg-epc-alpha-prototype-02.herokuapp.com/lodge-data
Based on one example there may be approx 20 screens of data to manually update
