### ISSUE TITLE
Full data driven service - multiple API end points etc...

### ISSUE THREAD

**Issue by davidtoldmeto** [notbinary/mhclg-epc-alpha#67]

**Comment by mcoulthurst** [comment]
The find-a-report path is fully dynamic, pulling data from the search and certificate pages.
The exception is the Certificate Number and Assessment Type, which don't appear in the API results.
The wireframe shows a history of reports lodged. I'm not clear where we can get this data
Still to do: Find-an-assessor, and opt-out address

**Comment by mcoulthurst** [comment]
Find-an-assessor and opt-out journey's have been split to have dummy data on the server. This is then rendered using nunjucks via the templates.
Multiple API end points have not been implemented yet. The opencommunities API doesn;t appear to have any additional info so putting that on hold until we need to add multiple data sources
